# Generated by Django 5.2.16 on 2026-07-27 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_follow_savedarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='إخفاء الكاتب من صفحات الموقع العامة'),
        ),
    ]
