# Generated by Django 5.2.16 on 2026-07-27 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name_en',
            field=models.CharField(blank=True, help_text='الاسم كما يظهر في النسخة الإنجليزية', max_length=120),
        ),
    ]
