# Generated by Django 5.2.16 on 2026-08-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='يجب على المستخدم تغيير كلمة المرور عند أول دخول'),
        ),
    ]
