# Generated by Django 5.2.16 on 2026-07-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=80, unique=True)),
                (
                    "league",
                    models.CharField(default="الدوري المصري الممتاز", max_length=120),
                ),
                ("home_team", models.CharField(max_length=120)),
                ("away_team", models.CharField(max_length=120)),
                ("home_score", models.SmallIntegerField(blank=True, null=True)),
                ("away_score", models.SmallIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "قادمة"),
                            ("live", "جارية"),
                            ("finished", "انتهت"),
                        ],
                        default="scheduled",
                        max_length=12,
                    ),
                ),
                ("kickoff_at", models.DateTimeField(blank=True, null=True)),
                ("round_label", models.CharField(blank=True, max_length=60)),
                ("venue", models.CharField(blank=True, max_length=160)),
            ],
            options={
                "verbose_name_plural": "matches",
                "ordering": ["-kickoff_at"],
            },
        ),
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.SlugField(max_length=40, unique=True)),
                ("label", models.CharField(max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "نجح"),
                            ("failed", "فشل"),
                            ("skipped", "متخطى"),
                        ],
                        default="skipped",
                        max_length=10,
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=300)),
                (
                    "records",
                    models.PositiveIntegerField(
                        default=0, help_text="عدد السجلات المحدَّثة في آخر تشغيل"
                    ),
                ),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("consecutive_failures", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["source"],
            },
        ),
        migrations.CreateModel(
            name="WireArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=200, unique=True)),
                ("title", models.CharField(max_length=400)),
                ("summary", models.TextField(blank=True)),
                ("url", models.URLField(max_length=600)),
                ("image_url", models.URLField(blank=True, max_length=600)),
                ("source_name", models.CharField(blank=True, max_length=120)),
                ("provider", models.SlugField(max_length=40)),
                ("language", models.CharField(default="ar", max_length=8)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-published_at", "-fetched_at"],
            },
        ),
        migrations.CreateModel(
            name="PrayerTimes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city_key", models.SlugField(max_length=30)),
                ("date", models.DateField()),
                ("hijri_date", models.CharField(blank=True, max_length=60)),
                ("fajr", models.CharField(blank=True, max_length=8)),
                ("dhuhr", models.CharField(blank=True, max_length=8)),
                ("asr", models.CharField(blank=True, max_length=8)),
                ("maghrib", models.CharField(blank=True, max_length=8)),
                ("isha", models.CharField(blank=True, max_length=8)),
            ],
            options={
                "verbose_name_plural": "prayer times",
                "ordering": ["-date"],
                "unique_together": {("city_key", "date")},
            },
        ),
    ]
