# Generated by Django 5.2.16 on 2026-07-27 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_article_subcategory'),
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='article',
            field=models.ForeignKey(blank=True, help_text='الخبر المرتبط — الضغط على الصورة في اللوحة يفتحه', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_assets', to='content.article'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='license',
            field=models.CharField(choices=[('owned', 'ملكية الدفتر'), ('agency', 'وكالة'), ('cc', 'المشاع الإبداعي'), ('permission', 'بإذن الناشر'), ('unknown', 'غير محدد')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='source',
            field=models.CharField(blank=True, help_text='الجهة أو الرابط الذي جاءت منه الصورة', max_length=200),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
