# Generated by Django 5.2.16 on 2026-07-26 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(allow_unicode=True, max_length=70, unique=True),
        ),
    ]
