# Generated by Django 5.2.16 on 2026-07-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_alter_tag_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, blank=True, max_length=300, unique=True
            ),
        ),
    ]
