# Generated by Django 5.2.16 on 2026-07-27 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='subcategory',
            field=models.CharField(blank=True, help_text='تصنيف فرعي يظهر كوسم أحمر على البطاقة', max_length=60),
        ),
    ]
