# Generated by Django 5.2.16 on 2026-07-28 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_article_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakingnewsitem',
            name='href',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
