# Generated by Django 5.2.16 on 2026-07-30 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_breakingnewsitem_href'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='country',
            field=models.CharField(blank=True, help_text='اسم الدولة — يظهر كشارة على صورة الخبر في «الخليج» و«عرب وعالم»', max_length=60),
        ),
    ]
