# Generated by Django 5.2.16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_article_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleblock',
            name='justify',
            field=models.BooleanField(default=False, help_text='ضبط النص (Justify) على هذه الفقرة'),
        ),
    ]
