# Generated by Django 5.2.16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_articleblock_justify'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='byline',
            field=models.CharField(blank=True, help_text='اسم الكاتب يُكتب يدوياً — يظهر تحت العنوان', max_length=120),
        ),
    ]
