# Generated by Django 5.2.16

from django.db import migrations, models


def carry_justify_into_align(apps, schema_editor):
    """A block already marked justify=True keeps meaning "justified" under
    the new field — the old boolean toggle becomes one of the four
    alignment choices instead of being silently discarded."""
    ArticleBlock = apps.get_model("content", "ArticleBlock")
    ArticleBlock.objects.filter(justify=True).update(align="justify")


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_article_byline'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleblock',
            name='align',
            field=models.CharField(
                choices=[('left', 'محاذاة اليسار'), ('center', 'محاذاة الوسط'), ('right', 'محاذاة اليمين'), ('justify', 'ضبط')],
                default='right',
                help_text='محاذاة الفقرة',
                max_length=10,
            ),
        ),
        migrations.RunPython(carry_justify_into_align, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='articleblock',
            name='justify',
        ),
    ]
