# Generated by Django 5.2.16 on 2026-08-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_articleblock_align'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='sections/'),
        ),
        migrations.AddField(
            model_name='section',
            name='tagline',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
