# Generated by Django 5.2.16 on 2026-08-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_section_cover_image_section_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='notify_label',
            field=models.CharField(blank=True, default='خبر عاجل', help_text='العنوان الفرعي للإشعار، مثال: "يحدث الآن"', max_length=40),
        ),
        migrations.AddField(
            model_name='article',
            name='notify_urgent',
            field=models.BooleanField(default=False, help_text='يظهر كإشعار عائم في كل صفحات الموقع لمدة 24 ساعة من النشر'),
        ),
    ]
