# Generated by Django 5.2.16 on 2026-08-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_article_notify_label_article_notify_urgent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleblock',
            name='align',
            field=models.CharField(choices=[('left', 'محاذاة اليسار'), ('center', 'محاذاة الوسط'), ('right', 'محاذاة اليمين'), ('justify', 'ضبط')], default='justify', help_text='محاذاة الفقرة', max_length=10),
        ),
    ]
