# Generated by Django 5.2.16 on 2026-08-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_alter_articleblock_align'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover_image_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='cover_image_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(blank=True, height_field='cover_image_height', null=True, upload_to='covers/', width_field='cover_image_width'),
        ),
    ]
