# Generated by Django 5.2.16 on 2026-09-03 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0015_article_cover_dimensions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="title",
            field=models.CharField(max_length=280),
        ),
    ]
