# Generated by Django 5.2.16 on 2026-07-27 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='external_url',
            field=models.URLField(blank=True, help_text='رابط فيديو خارجي بديلاً عن رفع الملف', max_length=500),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=300, unique=True),
        ),
    ]
