# Generated by Django 5.2.16 on 2026-07-28 03:10

from django.db import migrations, models


def approve_existing(apps, schema_editor):
    """
    Every comment that predates moderation was already live on its video
    page. The new field defaults to "pending", which the detail serializer
    now hides from anonymous readers — so without this step, applying the
    migration would silently retract comments that have been public for
    weeks. Only rows that exist at migration time are grandfathered in;
    everything submitted afterwards goes through the queue.
    """
    VideoComment = apps.get_model("video", "VideoComment")
    VideoComment.objects.update(status="approved")


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_video_external_url_alter_video_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocomment',
            name='status',
            field=models.CharField(choices=[('pending', 'معلّق'), ('approved', 'مقبول'), ('banned', 'محظور')], default='pending', max_length=10),
        ),
        # Reverse is a no-op: unapplying drops the column outright, so there
        # is no prior state left to restore.
        migrations.RunPython(approve_existing, migrations.RunPython.noop),
    ]
