# Generated by Django 5.2.16 on 2026-09-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0003_videocomment_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="reels/"),
                ),
                (
                    "facebook_url",
                    models.URLField(
                        help_text="رابط الريل على فيسبوك — البطاقة تفتحه في تبويب جديد",
                        max_length=500,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
