# Generated by Django 5.2.16 on 2026-09-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0004_reel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reel",
            name="title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
