# Generated by Django 5.2.16 on 2026-09-02 20:09, then hand-split into three
# safe steps — the autogenerated version added slug as unique=True in one
# step, which would try to give every EXISTING reel the same slug="" and fail
# the migration outright the moment there was a second row (both /srv this
# project's already had two live reels at the time this was written).
#
# 1. add the column, not yet unique — every existing row can share "" safely
# 2. backfill a real, distinct slug onto every existing row
# 3. only now add the unique constraint, once nothing can collide
#
# Step 1 uses a plain CharField, not SlugField, for the intermediate shape —
# SlugField implies db_index=True, which creates an index computed from the
# same table+column name step 3's unique constraint later needs. Both landed
# on the identical name (video_reel_slug_4bfe8bd6_like) with a real SlugField
# in both steps, so step 3 failed with "relation already exists" — inside the
# migration's own transaction, so nothing about it was visible afterwards to
# explain why, and every retry hit the identical failure. A CharField here
# carries no implicit index at all, so there is nothing for step 3 to collide
# with; the real SlugField shape (unique, allow_unicode) only exists once,
# in the final AlterField.

from django.db import migrations, models
from django.utils.text import slugify


def backfill_slugs(apps, schema_editor):
    Reel = apps.get_model("video", "Reel")
    # Not Reel.assign_slug(): migrations run against a frozen HISTORICAL
    # model, which does not carry the real model's methods — the logic is
    # inlined here instead, kept identical to Reel.assign_slug() on purpose.
    for reel in Reel.objects.all().order_by("pk"):
        base = slugify(reel.title, allow_unicode=True) or "reel"
        slug = base[:290]
        n = 2
        while Reel.objects.filter(slug=slug).exclude(pk=reel.pk).exists():
            slug = f"{base[:285]}-{n}"
            n += 1
        reel.slug = slug
        reel.save(update_fields=["slug"])


def noop_reverse(apps, schema_editor):
    # Nothing to undo — the AddField below (reversible on its own) is what a
    # rollback actually needs; the backfilled values just stop being used.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0005_alter_reel_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="reel",
            name="slug",
            field=models.CharField(blank=True, default="", max_length=300),
            preserve_default=False,
        ),
        migrations.RunPython(backfill_slugs, noop_reverse),
        migrations.AlterField(
            model_name="reel",
            name="slug",
            field=models.SlugField(allow_unicode=True, blank=True, max_length=300, unique=True),
        ),
    ]
