# Generated by Django 5.2.16 on 2026-07-26 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flag_emoji", models.CharField(default="🏳", max_length=8)),
                (
                    "code",
                    models.CharField(help_text="USD / EUR / GBP / SAR", max_length=6),
                ),
                ("buy", models.DecimalField(decimal_places=2, max_digits=10)),
                ("sell", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "change_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("is_up", models.BooleanField(default=True)),
                (
                    "series",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="آخر 8 قراءات لرسم الـsparkline",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "currencies",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="GoldKarat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="عيار 24 / عيار 21 / عيار 18 / جنيه ذهب",
                        max_length=40,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "change_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("is_up", models.BooleanField(default=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="TickerModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="currencies / gold / index / weather / oil",
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("label", models.CharField(max_length=60)),
                ("source", models.CharField(blank=True, max_length=120)),
                ("active", models.BooleanField(default=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="WeatherCity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="cairo / alex / luxor / aswan",
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("label", models.CharField(max_length=40)),
                ("icon", models.CharField(default="☀️", max_length=8)),
                ("temp", models.SmallIntegerField()),
                ("hi", models.SmallIntegerField()),
                ("lo", models.SmallIntegerField()),
                ("humidity", models.PositiveSmallIntegerField()),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "weather cities",
                "ordering": ["order", "id"],
            },
        ),
    ]
