# Generated by Django 5.2.16 on 2026-07-27 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickermodule',
            name='refresh_seconds',
            field=models.PositiveIntegerField(default=60, help_text='زمن إعادة جلب البيانات بالثواني (15 على الأقل)'),
        ),
    ]
