# Generated by Django 5.2.16 on 2026-07-26 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("visits", models.PositiveIntegerField(default=0)),
                (
                    "change_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(default="الدفتر نيوز", max_length=80)),
                (
                    "tagline",
                    models.CharField(
                        default="سِجلّ اليوم.. خبراً خبراً", max_length=140
                    ),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="branding/"),
                ),
                ("seo_title", models.CharField(blank=True, max_length=140)),
                ("seo_description", models.CharField(blank=True, max_length=300)),
                ("lang_ar_enabled", models.BooleanField(default=True)),
                ("lang_en_enabled", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "site settings",
            },
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("facebook", "فيسبوك"),
                            ("x", "X"),
                            ("instagram", "إنستغرام"),
                            ("youtube", "يوتيوب"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("url", models.URLField(blank=True)),
            ],
        ),
    ]
