# Generated by Django 5.2.16 on 2026-07-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WelcomeAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=False)),
                ("kicker", models.CharField(default="يحدث الآن", max_length=40)),
                ("title", models.CharField(blank=True, max_length=160)),
                ("text", models.CharField(blank=True, max_length=400)),
                ("cta_label", models.CharField(blank=True, max_length=60)),
                ("cta_href", models.CharField(blank=True, max_length=300)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="alerts/"),
                ),
            ],
            options={
                "verbose_name_plural": "welcome alert",
            },
        ),
    ]
