# Generated by Django 5.2.16 on 2026-08-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0003_pushsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(choices=[('facebook', 'فيسبوك'), ('x', 'X'), ('instagram', 'إنستغرام'), ('youtube', 'يوتيوب'), ('tiktok', 'تيك توك'), ('threads', 'Threads')], max_length=20, unique=True),
        ),
    ]
